### ISSUE TITLE
Document EM's and the unit() LESS function

### ISSUE THREAD

**Issue by himedlooff** [cfpb/capital-framework#10]
When using EM values I find it helpful to leave the calculation that got me the value inside of a comment. For example:

`font-size: 0.875em; /* 14/16 = 0.875 */`

This is helpful because it's hard to understand what these EM values mean sometimes. Like I haven't yet memorized that `0.875em` is `14px` in the context of `16px`. And if the context changes then it gets even more confusing.

The downside to commenting the calculation is it's harder to comment whole blocks of CSS because you can't do this:

``` css
/*.something {
  font-size: 0.875em; /* 14/16 = 0.875 */
}*/
```

I think it's worth it though because it makes it clear what that value is incase it needs to be adjusted later. Also this is only an issue when writing `.css` files.

With LESS you can use LESS comments which you can wrap with standard CSS comments like this:

``` less
/*.something {
  font-size: 0.875em; // 14/16 = 0.875
}*/
```

OR... I've been playing around with the `unit()` function which allows you to use a math expression inside of it. This is nice because the calculation is not inside of a comment anymore. Also when you need to calculate margins or other properties in EM's where the context is likely to affect the calculation it's much easier to do.

_When changing from 22px to 28px font-size it's pretty easy:_

``` less
h1 {
    font-size: unit( 22 / @base-font-size-px, em );
    margin: unit( 10 / 22, em ) 0;
}
```

``` less
h1 {
    font-size: unit( 28 / @base-font-size-px, em );
    margin: unit( 10 / 28, em ) 0;
}
```
