### ISSUE TITLE
Semantic color vars

### ISSUE THREAD

**Issue by himedlooff** [cfpb/capital-framework#115]
https://github.com/cfpb/capital-framework/issues/99 sparked the idea of using better color var names like `@primary-action` instead of straight up using `@pacific`.

**Comment by himedlooff** [comment]
I think what might be helpful is to see all of the colors used in Capital Framework. I'll update this comment as I go through each component:

# cf-core

| use | brand color |
| --- | ----------- |
| base-text-color | `@black` |
| base-link-color | `@pacific` |
| base-link-color-visited | `@teal` |
| base-link-color-hover | `@pacific-50` |
| base-link-color-active | `@navy` |
| table-head-bg | `@darkgray` |
| table-head-color | `@white` |
| tr-stripe | `@gray-5` |
| tr-stripe-alt | `@gray-5` |
| pullquote-citation | `@gray-10` |
| input-bg | `@white` |
| input-border | `@pacific` |
| input-border-focus | `@pacific` |
| input-placeholder | `@gray` |
| figure-bordered-img | `@gray-50` |
| branded-list-bullet | `@green` |

**Comment by himedlooff** [comment]
Here is the current proposal that myself, @Scotchester and @virginiacc chatted about today. We'd like to run it by others, especially @ascott1, @contolini, @wernerc, @sephcoster, and @awolfe76.

The **goal** of this proposal is to allow non-CFPB Capital Framework users to more easily customize the framework colors.

- If you like the idea then please give a :+1:.
- If you have concerns then please note them here. I'm going to set up a meeting invite for tomorrow (1/13) at 3pm. We can talk about any big issues at that time.

I know some of you may be very busy with the incoming fellows so if you do have concerns and can't make it please let me know here. Also if this makes no sense to you or if something isn't clearly explained, please let me know.

# Capital Framework color variables proposal

- Capital Framework will not use CFPB-branded colors or color variables for any
UI elements.
- As a result, docs for components will no longer be CFPB-branded and the Design Manual will
become the new go-to place to review CFPB-Branded Capital Framework patterns.
- The unbranded docs will still be the go-to source for code-related documentation.

## What does this achieve?

Approaching color variables in this way will force CF-development to assume the
perspective of a non-CFPB user and make customizing colors across the framework
much easier. It also helps to tie Captial Framework and Design Manual development
together in a way that has previously been lacking. This could lay the groundwork
for allowing non-CFPB users to fork the Design Manual, override the colors, and
create their own custom-branded Design Manual.

## How would it work?

To add custom branding to a Captial Framework project, you simply need to override
color variables in one locations, `cf-var-overrides.less`. This is an optional
and project-specific file, meaning it is not needed to compile the framework or
a component and is not needed or used to compile the docs when working on a component.
The file lists all of the color variables used across all Capital Framework
components, and from here, you can architect and override color variables in any
way that you want. CFPB projects can pull in a globally shared `cfpb-brand-colors.less`
and `cf-var-overrides.less` file, which will provide the proper CFPB-branded overrides for
all Capital Framework components.

# Examples

## Updates to cf-base.less within the cf-core component

```less
@link-color: #some-non-cfpb-hex;
@link-color-hover: #another-non-cfpb-hex;

a {
    color: @link-color;
    &:hover {
        colore: @link-color-hover;
    }
}
```

## Updates to cf-buttons.less within the cf-button component

```less
@btn-primary: #some-non-cfpb-hex;
@btn-primary-hover: fade(@btn-primary);
@btn-primary-color: #some-non-cfpb-hex;

@btn-secondary: #some-non-cfpb-hex;
@btn-secondary-hover: fade(@btn-secondary);
@btn-secondary-color: #some-non-cfpb-hex;

.btn {
    background: @btn-primary;
    color: @btn-primary-color;
    &:hover {
        background: @btn-primary-hover;
    }
}

.btn__secondary {
    background: @btn-secondary;
    color: @btn-secondary-color;
    &:hover {
        background: @btn-secondary-hover;
    }
}
```

# cf-vars-override.less within a CFPB project

```less
@import "cf-brand-colors.less";

// cf-core overrides

@link-color: @pacific;
@link-color-hover: @pacific-hover;

// cf-buttons overrides

@btn-primary: @pacific;
@btn-primary-hover: @pacific-80;
@btn-primary-color: @white;

@btn-secondary: @gray;
@btn-secondary-hover: @darkgray;
@btn-secondary-color: @white;
```

# An example of cf-vars-override.less within a non-CFPB project

```less
// My brand colors
@brand-color: #some-hex;
@primary-action: #some-hex;
@secondary-action: #some-hex;
@white: #some-hex;

// cf-core overrides

@link-color: @primary-action;
@link-color-hover: fade(@primary-action, 50%);

// cf-buttons overrides

@btn-primary: @primary-action;
@btn-primary-hover: fade(@primary-action, 25%);
@btn-primary-color: @white;

@btn-secondary: @secondary-action;
@btn-secondary-hover: darken(@secondary-action, 25%);
@btn-secondary-color: @white;
```
