### ISSUE TITLE
[cf-core] Standardize visual offsets with helper function

### ISSUE THREAD

**Issue by anselmbradford** [cfpb/capital-framework#209]
There are places in the flapjack/v1 codebase where margin or padding is offset to align with design specs to take into account line-height irregularities of a font, etc. Currently this are tracked through arbitrary code comments that include "eyeballed", "optical offset", "visually offset", etc.

I'd like to propose we create a helper function to make it clearer when something is being visually offset from a standard value that can be used in place of the arbitrary hardcoded pixel values that often get used.

How about:

```less
// Helper function
.u-offset( @base-val, @offset) {
  @u-offset: @base-val + @offset;
}

…

// Use of helper
.u-offset(30px, -5px);
margin-left: unit(@u-offset, em); // 30px standard, visually offset to 25px
```

> NOTE: I wish it could be a single thing that returns a value, like `margin-left: unit(u-offset(30px, -5px), em);`, but I don't see how that's possible in Less. If someone knows a way, pipe up!
