### ISSUE TITLE
[cf-core] Include classes for table element display aliases 

### ISSUE THREAD

**Issue by KimberlyMunoz** [cfpb/capital-framework#215]
Original Issue:  https://github.com/cfpb/cf-core/issues/41

In some cases it's valuable to use `display: table-*` properties to build a table, for example:

- As a fallback for flexbox.
- To allow a table row to be a link.
- To use table-like layout in places where a table isn't semantically correct.

Can cf-core provide utility class mappings for table element --> table display property? 
Like:

```css
.u-table { display: table; }
.u-table-caption { display: table-caption; }
.u-colgroup { display: table-column-group; }
.u-thead { display: table-header-group; }
.u-tfoot { display: table-footer-group; }
.u-tbody { display: table-row-group; }
.u-col { display: table-column; }
.u-tr { display: table-row; }
.u-td, .u-th { display: table-cell; }
```
